//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThueXeOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Khach()
        {
            this.HopDongs = new HashSet<HopDong>();
        }
    
        public int MaKhach { get; set; }
        public string TenKhach { get; set; }
        public string DiaChi { get; set; }
<<<<<<< HEAD
=======
        [Display(Name = "CMTND")]
        [Required(ErrorMessage = "{0} Không Được Để Trống")]
>>>>>>> c5905d54c4c85040ca7c0b133565208e376b2b35
        public string CMTND { get; set; }
        public string SoDT { get; set; }
        public string SoTK { get; set; }
        public string NganHang { get; set; }
        public string TenCQ { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string email { get; set; }
    
<<<<<<< HEAD
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
=======
>>>>>>> c5905d54c4c85040ca7c0b133565208e376b2b35
        public virtual ICollection<HopDong> HopDongs { get; set; }
    }
}
